
- name: Ensure our bould env is created
  ansible.builtin.shell: mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
  args:
    chdir: /var
  become: True





- name: " build_virtual_environments |  Running downloader script to collect python sources"
  ansible.builtin.shell: /var/lib/openstack/venv/builder/venv/bin/python /usr/local/bin/pip-downloader.py
  args:
    chdir: /var/lib/openstack/venv/{{ project }}/{{ version }}
  become: True
