- include: redhat.yaml
- include: sclmetapackage.yml
- include: sclbuilder.yaml

#- include: build_virtual_environments.yaml
#- include: download_pip_sources.yaml
#- include: build_scl_rpm.yaml
#- include: checkout_source.yaml


