####################################################
# What to be done om redhat only
####################################################

- name: check if we're building on a supported os
  assert:
    fail_msg: "{{ role_name }} only supports ubuntu versions 16, 18, 20 and centos versions 6, 7!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      ansible_distribution|lower == "redhat" and ansible_distribution_major_version|int in [8] 

- name: ansible_role_build_ostack_components | Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Enable codeready-builder repository
  shell: subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
  become: True

- name: build_virtual_environments | Install tools on build servers
  ansible.builtin.package:
    name:  '{{ item  }}'
    state: present
  with_items:
    - "git"
    - "python3-pip"
    - "python3-devel"
    - "python3-setuptools-wheel"
    - "make" 
    - "autoconf" 
    - "automake" 
    - "libtool" 
    - "gcc"
    - "zlib-devel"
    - "rpm-build"
    - "tree"
    - "python3-virtualenv"
    - "help2man"
    - "scl-utils-build"
    - "scl-utils"
    - "libffi-devel"


      #    - "liberasurecode-devel"
